# Generated by Django 4.1.2 on 2023-02-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('items', models.JSONField(null=True)),
                ('tier', models.JSONField(null=True)),
                ('rarity', models.IntegerField(null=True)),
                ('fre', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('winrate', models.FloatField(max_length=30, null=True)),
                ('windefencerate', models.FloatField(max_length=30, null=True)),
                ('avgplace', models.FloatField(max_length=30, null=True)),
                ('units', models.JSONField(null=True)),
                ('core', models.JSONField(null=True)),
                ('augments', models.JSONField(null=True)),
                ('traits', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeckData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('placement', models.IntegerField(null=True)),
                ('units1', models.JSONField(null=True)),
                ('coreunits1', models.JSONField(null=True)),
                ('units2', models.JSONField(null=True)),
                ('coreunits2', models.JSONField(null=True)),
                ('augments1', models.JSONField(null=True)),
                ('augments2', models.JSONField(null=True)),
                ('H_aug1', models.CharField(max_length=30, null=True)),
                ('H_aug2', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('matchId', models.CharField(max_length=30)),
                ('info', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Summoner_rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('puuid', models.CharField(max_length=100)),
                ('profileIconID', models.IntegerField(null=True)),
                ('tier', models.CharField(max_length=30, null=True)),
                ('LP', models.CharField(max_length=30, null=True)),
                ('winrate', models.CharField(max_length=30, null=True)),
                ('game_num', models.IntegerField(null=True)),
                ('win', models.IntegerField(null=True)),
                ('lose', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
