# Generated by Django 4.1.2 on 2023-02-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='h_aug',
            field=models.JSONField(null=True),
        ),
    ]
