# Generated by Django 4.1.2 on 2023-01-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='info',
            field=models.TextField(),
        ),
    ]
