# Generated by Django 4.1.2 on 2023-01-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_match_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='info',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchId',
            field=models.TextField(unique=True),
        ),
    ]
