# Generated by Django 4.1.2 on 2023-02-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_deck_h_aug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('units', models.JSONField(null=True)),
                ('fre', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
