# Generated by Django 4.1.2 on 2023-01-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_match_info_alter_match_matchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='matchId',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Combinations_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.JSONField(null=True)),
                ('traits', models.JSONField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.match')),
            ],
        ),
        migrations.CreateModel(
            name='Combinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.JSONField(null=True)),
                ('traits', models.JSONField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.match')),
            ],
        ),
    ]
