# Generated by Django 4.1.2 on 2023-02-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_standarddeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarddeck',
            name='partner',
            field=models.JSONField(null=True),
        ),
    ]
