# Generated by Django 4.1.2 on 2023-02-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_standarddeck_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('placement', models.IntegerField(null=True)),
                ('units', models.JSONField(null=True)),
                ('traits', models.JSONField(null=True)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.standarddeck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
