# Generated by Django 4.1.2 on 2023-02-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_standarddeck_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerdeck',
            old_name='placement',
            new_name='win',
        ),
        migrations.RemoveField(
            model_name='partnerdeck',
            name='traits',
        ),
    ]
