# Generated by Django 4.1.2 on 2023-01-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='tier',
            field=models.IntegerField(null=True),
        ),
    ]
