# Generated by Django 4.1.2 on 2023-02-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_placement_partnerdeck_win_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdeck',
            name='fre',
            field=models.IntegerField(null=True),
        ),
    ]
