# Generated by Django 4.1.2 on 2023-01-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_champion_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='rarity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='tier',
            field=models.JSONField(null=True),
        ),
    ]
