# Generated by Django 4.1.2 on 2023-01-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_champion_rarity_alter_champion_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='combinations',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='combinations_partner',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='summoner_rank',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
