# Generated by Django 4.1.2 on 2023-02-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_partnerdeck_fre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerdeck',
            old_name='win',
            new_name='windef',
        ),
    ]
