# Generated by Django 4.1.2 on 2023-01-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_champion_updated_time_combinations_updated_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='champion',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='combinations',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='combinations_partner',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='summoner_rank',
            name='updated_time',
        ),
    ]
