# Generated by Django 4.1.2 on 2023-01-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_time_remove_champion_updated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='modelName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
