# Generated by Django 4.1.2 on 2023-01-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_time_modelname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time',
            new_name='Update',
        ),
    ]
