# Generated by Django 4.1.2 on 2023-02-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_remove_partnerdeck_fre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('winrate', models.FloatField(max_length=30, null=True)),
                ('windefencerate', models.FloatField(max_length=30, null=True)),
                ('avgplace', models.FloatField(max_length=30, null=True)),
                ('units', models.JSONField(null=True)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.standarddeck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
