# Generated by Django 4.1.2 on 2023-01-20 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_rename_time_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='Time',
        ),
    ]
