# Generated by Django 4.1.2 on 2023-01-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_rename_update_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AddField(
            model_name='champion',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='combinations',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='combinations_partner',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='summoner_rank',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
