# Generated by Django 4.1.2 on 2023-01-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_delete_time_champion_updated_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('placement', models.IntegerField(null=True)),
                ('units1', models.JSONField(null=True)),
                ('units2', models.JSONField(null=True)),
                ('augments1', models.JSONField(null=True)),
                ('augments2', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
