# Generated by Django 4.1.2 on 2023-01-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_deck'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deck',
            new_name='DeckData',
        ),
    ]
