# Generated by Django 4.1.2 on 2023-02-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_standarddeck_avgplace_standarddeck_windefencerate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarddeck',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
