# Generated by Django 4.1.2 on 2023-01-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_rename_deck_deckdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('win_rate', models.CharField(max_length=30, null=True)),
                ('windefense_rate', models.CharField(max_length=30, null=True)),
                ('place_avg', models.CharField(max_length=30, null=True)),
                ('game_num', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
