# Generated by Django 4.1.2 on 2023-02-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_standarddeck_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarddeck',
            name='placement',
            field=models.JSONField(null=True),
        ),
    ]
