# Generated by Django 4.1.2 on 2023-02-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_standarddeck_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarddeck',
            name='H_aug',
            field=models.JSONField(null=True),
        ),
    ]
