# Generated by Django 4.1.2 on 2023-02-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_alter_standarddeck_h_aug'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarddeck',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
