# Generated by Django 4.1.2 on 2023-03-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_standarddeck_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('units', models.JSONField(null=True)),
                ('coreunits', models.JSONField(null=True)),
                ('augments', models.JSONField(null=True)),
                ('H_aug', models.JSONField(null=True)),
                ('fre', models.IntegerField(null=True)),
                ('placement', models.JSONField(null=True)),
                ('winrate', models.FloatField(null=True)),
                ('windefencerate', models.FloatField(null=True)),
                ('avgplace', models.FloatField(null=True)),
                ('parentsdeck', models.ForeignKey(db_column='parents_id', on_delete=django.db.models.deletion.CASCADE, to='data.standarddeck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
