# Generated by Django 4.1.2 on 2023-03-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_doubledeck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubledeck',
            name='H_aug',
        ),
        migrations.RemoveField(
            model_name='doubledeck',
            name='augments',
        ),
        migrations.RemoveField(
            model_name='doubledeck',
            name='coreunits',
        ),
        migrations.RemoveField(
            model_name='doubledeck',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doubledeck',
            name='units',
        ),
        migrations.AddField(
            model_name='doubledeck',
            name='deck_id',
            field=models.IntegerField(null=True),
        ),
    ]
