# Generated by Django 4.1.2 on 2023-01-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_rename_c_augment_deck_winrate_remove_deck_placement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='avgplace',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='pickrate',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='windefencerate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
