# Generated by Django 4.1.2 on 2023-01-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_deck_avgplace_deck_pickrate_deck_windefencerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckdata',
            name='coreunits1',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='deckdata',
            name='coreunits2',
            field=models.JSONField(null=True),
        ),
    ]
