# Generated by Django 4.1.2 on 2023-01-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_deckdata_coreunits1_deckdata_coreunits2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='name',
        ),
    ]
