# Generated by Django 4.1.2 on 2023-01-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_remove_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='core',
            field=models.JSONField(null=True),
        ),
    ]
