# Generated by Django 4.1.2 on 2023-01-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_alter_deck_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='avgplace',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='pickrate',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='windefencerate',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='winrate',
            field=models.FloatField(max_length=30, null=True),
        ),
    ]
