# Generated by Django 4.1.2 on 2023-01-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_alter_deck_avgplace_alter_deck_pickrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='pickrate',
        ),
    ]
