# Generated by Django 4.1.2 on 2023-01-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_remove_deck_pickrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='traits',
            field=models.JSONField(null=True),
        ),
    ]
