# Generated by Django 4.1.2 on 2023-02-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_alter_deck_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
