# Generated by Django 4.1.2 on 2023-02-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_champion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner_rank',
            name='profileIconId',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
