# Generated by Django 4.1.2 on 2023-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_alter_summoner_rank_profileiconid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner_rank',
            name='profileIconId',
        ),
        migrations.AddField(
            model_name='summoner_rank',
            name='profileIconID',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
