# Generated by Django 4.1.2 on 2023-02-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_remove_summoner_rank_profileiconid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner_rank',
            name='profileIconID',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
