# Generated by Django 4.1.2 on 2023-02-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_alter_summoner_rank_profileiconid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner_rank',
            name='profileIconID',
            field=models.IntegerField(null=True),
        ),
    ]
