# Generated by Django 4.1.2 on 2023-02-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_alter_summoner_rank_profileiconid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='image',
        ),
    ]
