# Generated by Django 4.1.2 on 2023-02-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_remove_champion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckdata',
            name='H_aug1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deckdata',
            name='H_aug2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
