# Generated by Django 4.1.2 on 2023-02-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_deckdata_h_aug1_deckdata_h_aug2'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='fre',
            field=models.IntegerField(null=True),
        ),
    ]
